-- MySQL Script generated by MySQL Workbench
-- Thu Jan 17 21:57:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema usine_sens
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usine_sens
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usine_sens` DEFAULT CHARACTER SET utf8 ;
USE `usine_sens` ;

-- -----------------------------------------------------
-- Table `usine_sens`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `avatar` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `firstname` VARCHAR(150) NOT NULL,
  `date_creation` DATETIME NULL,
  `push` TINYINT(1) NULL,
  `token` CHAR(128) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usine_sens`.`interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`interest` (
  `id_interest` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id_interest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usine_sens`.`workshop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`workshop` (
  `id_workshop` INT NOT NULL AUTO_INCREMENT,
  `duration` TIME NULL,
  `name` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `place` VARCHAR(255) NULL,
  `price` FLOAT NULL,
  `date_start` DATETIME NULL,
  `date_end` DATETIME NULL,
  PRIMARY KEY (`id_workshop`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usine_sens`.`sense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`sense` (
  `id_sens` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `active` TINYINT(1) NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id_sens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usine_sens`.`exposition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`exposition` (
  `id_exposition` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `place` VARCHAR(45) NULL,
  `date_start` DATETIME NULL,
  `date_end` DATETIME NULL,
  PRIMARY KEY (`id_exposition`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usine_sens`.`coworking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`coworking` (
  `id_coworking` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `price` FLOAT NULL,
  `date_start` DATETIME NULL,
  `date_end` DATETIME NULL,
  PRIMARY KEY (`id_coworking`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usine_sens`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`room` (
  `id_room` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `date_start` DATETIME NULL,
  `date_end` DATETIME NULL,
  `number_of_guests` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `cleaning_time` TIME NULL,
  PRIMARY KEY (`id_room`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usine_sens`.`user_has_interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`user_has_interest` (
  `user_id_user` INT NOT NULL,
  `interest_id_interest` INT NOT NULL,
  PRIMARY KEY (`user_id_user`, `interest_id_interest`),
  INDEX `fk_user_has_interest_interest1_idx` (`interest_id_interest` ASC) VISIBLE,
  INDEX `fk_user_has_interest_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_interest_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `usine_sens`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_interest_interest1`
    FOREIGN KEY (`interest_id_interest`)
    REFERENCES `usine_sens`.`interest` (`id_interest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usine_sens`.`user_has_exposition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`user_has_exposition` (
  `user_id_user` INT NOT NULL,
  `exposition_id_exposition` INT NOT NULL,
  PRIMARY KEY (`user_id_user`, `exposition_id_exposition`),
  INDEX `fk_user_has_exposition_exposition1_idx` (`exposition_id_exposition` ASC) VISIBLE,
  INDEX `fk_user_has_exposition_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_exposition_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `usine_sens`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_exposition_exposition1`
    FOREIGN KEY (`exposition_id_exposition`)
    REFERENCES `usine_sens`.`exposition` (`id_exposition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usine_sens`.`user_has_workshop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`user_has_workshop` (
  `user_id_user` INT NOT NULL,
  `workshop_id_workshop` INT NOT NULL,
  PRIMARY KEY (`user_id_user`, `workshop_id_workshop`),
  INDEX `fk_user_has_workshop_workshop1_idx` (`workshop_id_workshop` ASC) VISIBLE,
  INDEX `fk_user_has_workshop_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_workshop_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `usine_sens`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_workshop_workshop1`
    FOREIGN KEY (`workshop_id_workshop`)
    REFERENCES `usine_sens`.`workshop` (`id_workshop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usine_sens`.`user_has_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`user_has_room` (
  `user_id_user` INT NOT NULL,
  `room_id_room` INT NOT NULL,
  PRIMARY KEY (`user_id_user`, `room_id_room`),
  INDEX `fk_user_has_room_room1_idx` (`room_id_room` ASC) VISIBLE,
  INDEX `fk_user_has_room_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_room_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `usine_sens`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_room_room1`
    FOREIGN KEY (`room_id_room`)
    REFERENCES `usine_sens`.`room` (`id_room`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usine_sens`.`user_has_coworking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`user_has_coworking` (
  `user_id_user` INT NOT NULL,
  `coworking_id_coworking` INT NOT NULL,
  PRIMARY KEY (`user_id_user`, `coworking_id_coworking`),
  INDEX `fk_user_has_coworking_coworking1_idx` (`coworking_id_coworking` ASC) VISIBLE,
  INDEX `fk_user_has_coworking_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_coworking_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `usine_sens`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_coworking_coworking1`
    FOREIGN KEY (`coworking_id_coworking`)
    REFERENCES `usine_sens`.`coworking` (`id_coworking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usine_sens`.`workshop_has_sense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`workshop_has_sense` (
  `workshop_id_workshop` INT NOT NULL,
  `sense_id_sens` INT NOT NULL,
  PRIMARY KEY (`workshop_id_workshop`, `sense_id_sens`),
  INDEX `fk_workshop_has_sense_sense1_idx` (`sense_id_sens` ASC) VISIBLE,
  INDEX `fk_workshop_has_sense_workshop1_idx` (`workshop_id_workshop` ASC) VISIBLE,
  CONSTRAINT `fk_workshop_has_sense_workshop1`
    FOREIGN KEY (`workshop_id_workshop`)
    REFERENCES `usine_sens`.`workshop` (`id_workshop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workshop_has_sense_sense1`
    FOREIGN KEY (`sense_id_sens`)
    REFERENCES `usine_sens`.`sense` (`id_sens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usine_sens`.`exposition_has_sense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`exposition_has_sense` (
  `exposition_id_exposition` INT NOT NULL,
  `sense_id_sens` INT NOT NULL,
  PRIMARY KEY (`exposition_id_exposition`, `sense_id_sens`),
  INDEX `fk_exposition_has_sense_sense1_idx` (`sense_id_sens` ASC) VISIBLE,
  INDEX `fk_exposition_has_sense_exposition1_idx` (`exposition_id_exposition` ASC) VISIBLE,
  CONSTRAINT `fk_exposition_has_sense_exposition1`
    FOREIGN KEY (`exposition_id_exposition`)
    REFERENCES `usine_sens`.`exposition` (`id_exposition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exposition_has_sense_sense1`
    FOREIGN KEY (`sense_id_sens`)
    REFERENCES `usine_sens`.`sense` (`id_sens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usine_sens`.`room_has_sense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`room_has_sense` (
  `room_id_room` INT NOT NULL,
  `sense_id_sens` INT NOT NULL,
  PRIMARY KEY (`room_id_room`, `sense_id_sens`),
  INDEX `fk_room_has_sense_sense1_idx` (`sense_id_sens` ASC) VISIBLE,
  INDEX `fk_room_has_sense_room1_idx` (`room_id_room` ASC) VISIBLE,
  CONSTRAINT `fk_room_has_sense_room1`
    FOREIGN KEY (`room_id_room`)
    REFERENCES `usine_sens`.`room` (`id_room`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_has_sense_sense1`
    FOREIGN KEY (`sense_id_sens`)
    REFERENCES `usine_sens`.`sense` (`id_sens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `usine_sens` ;

-- -----------------------------------------------------
-- Placeholder table for view `usine_sens`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usine_sens`.`view1` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `usine_sens`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `usine_sens`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usine_sens`.`view1`;
USE `usine_sens`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
